@url = http://localhost:5000
@username = adam.bartski
@email = adam.bartski@gmail.com
@password = password

###
### REGISTER ACCOUNT
###
# @name register
POST {{url}}/account/register
content-type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

###
### LOGIN
###
# @name login
POST {{url}}/account/login
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
### CHECK AUTH
### 
# @name check-auth
GET {{url}}/account/check-auth
Authorization: Bearer {{login.response.body.token}}

###
### REFRESH TOKEN
### 
# @name refresh-token
POST {{url}}/account/tokens/refresh
Authorization: Bearer {{login.response.body.token}}
content-type: application/json

{
  "token": "{{login.response.body.refreshToken}}"
}

###
### REVOKE REFRESH TOKEN
### 
# @name refresh-token
POST {{url}}/account/tokens/revoke
Authorization: Bearer {{login.response.body.token}}
content-type: application/json

{
  "token": "{{login.response.body.refreshToken}}"
}