@url = http://localhost:5000
@username = adam.bartski
@email = adam.bartski@gmail.com
@password = password

###
### REGISTER ACCOUNT
###
# @name register
POST {{url}}/account/register
content-type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

###
### LOGIN
###
# @name login
POST {{url}}/account/login
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
### CHECK AUTH
### 
# @name checkAuth
GET {{url}}/account/check-auth
Authorization: Bearer {{login.response.body.token}}

###
### REFRESH TOKEN
### 
# @name refreshToken
POST {{url}}/token/refresh
Authorization: Bearer {{login.response.body.token}}
content-type: application/json

{
  "refreshToken": "{{login.response.body.refreshToken}}"
}

###
### REVOKE REFRESH TOKEN
### 
# @name revokeToken
POST {{url}}/token/revoke
Authorization: Bearer {{login.response.body.token}}
content-type: application/json

{
  "refreshToken": "{{login.response.body.refreshToken}}"
}

###
### GET USER BY EMAIL
###
# @name getUserByEmail
GET {{url}}/users
Authorization: Bearer {{login.response.body.token}}
content-type: application/json

{
  "email": "{{email}}"
}

###
### CREATE POST
###
# @name createPost
POST {{url}}/posts
Authorization: Bearer {{login.response.body.token}}
content-type: application/json

{
  "content": "Post dupa dupa"
}

###
### CREATE POST
###
# @name getPostById
GET {{url}}/{{createPost.response.headers.Location}}
Authorization: Bearer {{login.response.body.token}}
